[package]
name = "the-little-typer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
maplit = "1.0"
sexpr_parser = "0.1"
